[project]
name = "youtubesupplementarymaterials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.4.0",
    "numpy>=1.21.0",
    "pyqt6>=6.4.0",
]
